
---
- hosts: all
  become: true
  tasks:
  
  - name: to install apache
    apt: name=apache2 state=latest
    when: ansible_distribution == 'Ubuntu'
    notify: 
        - start apache

  - name: to install http 
    yum: name=httpd state=latest
    when: ansible_distribution == 'CentOS'
    notify:
        - start httpd

  handlers:
  - name: start apache
    service: name=apache2 state=started
  
  - name: start httpd
    service: name=httpd state=started




